// Mocks generated by Mockito 5.4.4 from annotations
// in logbook_app_01/test/modul4_saveToCloud_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:connectivity_plus/connectivity_plus.dart' as _i5;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i6;
import 'package:logbook_app_01/features/logbook/models/log_model.dart' as _i4;
import 'package:logbook_app_01/features/logbook/services/mongo_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MongoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMongoService extends _i1.Mock implements _i2.MongoService {
  MockMongoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.LogModel>> getLogsByTeam(String? teamId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogsByTeam,
          [teamId],
        ),
        returnValue: _i3.Future<List<_i4.LogModel>>.value(<_i4.LogModel>[]),
      ) as _i3.Future<List<_i4.LogModel>>);

  @override
  _i3.Future<void> insertLog(_i4.LogModel? log) => (super.noSuchMethod(
        Invocation.method(
          #insertLog,
          [log],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateLog(_i4.LogModel? log) => (super.noSuchMethod(
        Invocation.method(
          #updateLog,
          [log],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLog(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLog,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i5.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i3.Stream<List<_i6.ConnectivityResult>>.empty(),
      ) as _i3.Stream<List<_i6.ConnectivityResult>>);

  @override
  _i3.Future<List<_i6.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i3.Future<List<_i6.ConnectivityResult>>.value(
            <_i6.ConnectivityResult>[]),
      ) as _i3.Future<List<_i6.ConnectivityResult>>);
}
